package:
    name:           hidev-config-php
    namespace:      hiqdev\hidev\config\php
    headline:       HiDev PHP
    title:          HiDev config for PHP projects
    type:           yii2-extension
    keywords:       hidev, config, php
    year:           2015
    description:    |
        All you need for PHP projects:
        - standart: .gitignore, LICENSE, README.md, CHANGELOG.md
        - composer.json
        - php-cs-fixer
        - codeception

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
